# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c2bc572ca1c7a58f5988e2e74eee3612353a484d92c794495b7be1b44260c2177777662e9df2fdc5feab14b47cef1b4ca77c27eff7382538a9a2eb522c4e5b1f

test:
  secret_key_base: 65891f8aaf8efaf3499d565267c52e36b3ef72be46417b86ed35bc7385b660aeee8c96c92104712dcedfe9c0d92b0e87797e6548ed26378e744104de7c304c63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
